const motivationalQuotes = [
  "Start where you are. Use what you have. Do what you can.",
  "The secret to getting ahead is getting started.",
  "Done is better than perfect.",
  "Action breeds confidence and courage.",
  "The best way to get something done is to begin.",
  "A journey of a thousand miles begins with a single step.",
  "Progress, not perfection.",
  "Your future is created by what you do today, not tomorrow.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Little by little, one travels far.",
  "Big things happen one step at a time.",
  "Success is the sum of small efforts repeated daily.",
  "Discipline is doing it even when you don’t feel like it.",
  "Dream big. Start small. Act now.",
  "Every accomplishment starts with the decision to try.",
  "Don’t break the chain — keep going.",
  "A to-do list is a roadmap to your future self.",
  "You don’t have to be extreme, just consistent.",
  "Focus on the step in front of you, not the whole staircase.",
  "Great things are not done by impulse, but by a series of small things.",
  "Turn your 'one day' into 'day one'.",
  "Small tasks completed lead to big victories.",
  "The first step is the hardest — take it anyway.",
  "Be stronger than your excuses.",
  "Your goals don’t work unless you do.",
  "You are one task closer to your dreams.",
  "What you do today can improve all your tomorrows.",
  "It always seems impossible until it’s done.",
  "Make it happen. Shock everyone.",
  "You owe it to yourself to finish what you start.",
  "Start strong. Finish stronger.",
  "Push yourself. No one else will do it for you.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Win the day. One task at a time.",
  "Clarity comes from engagement, not thought.",
  "Don’t be busy. Be productive.",
  "One task at a time. One victory at a time.",
  "Get it done and get on with life.",
  "Start small. Stay focused. Keep going.",
  "You’re not behind — you’re just getting started.",
  "Finish what you start. That’s how you build confidence.",
  "Your future self will thank you.",
  "Don’t think. Just do.",
  "Productivity is the engine of progress.",
  "Momentum builds from action, not intention.",
  "Clear tasks. Clear mind.",
  "You’re closer than you think.",
  "Make your to-do list your ta-da list.",
  "Finish the task. Own the day.",
  "Get up. Get it done. Repeat.",
];

export default motivationalQuotes;
